require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2

Style/Documentation:
  Enabled: false

Capybara/ClickLinkOrButtonStyle:
  Enabled: false
